from selenium import webdriver
import time

from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service

class logininputs:
    def inputslog(self):
        options = webdriver.ChromeOptions()
        options.add_experimental_option("detach", True)
        driver = webdriver.Chrome(options=options, service=Service(ChromeDriverManager().install()))
        driver.get("http://localhost/opencart/upload/index.php?route=common/home&language=en-gb")
        driver.find_element(By.XPATH, "//span[normalize-space()='My Account']").click()
        driver.find_element(By.XPATH, "//a[@class='dropdown-item'][normalize-space()='Login']").click()
        driver.find_element(By.XPATH,"//input[@id='input-email']").send_keys("a@gmail.com")
        driver.find_element(By.CSS_SELECTOR,"#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR,"button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        time.sleep(1)
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("b@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("121456")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        # time.sleep(2)
        driver.find_element(By.XPATH,"//input[@id='input-email']").send_keys("c@gmail.com")
        driver.find_element(By.CSS_SELECTOR,"#input-password").send_keys("1214587")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        # driver.find_element(By.CSS_SELECTOR,"button[type='submit']").click()
        # time.sleep(1)
        driver.find_element(By.XPATH,"//input[@id='input-email']").send_keys("e@gmail.com")
        driver.find_element(By.CSS_SELECTOR,"#input-password").send_keys("wwwec")
        driver.find_element(By.CSS_SELECTOR,"button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        # time.sleep(1)
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("l@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("1214521")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        # time.sleep(1)
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("rt@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("asdf")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        # time.sleep(1)
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("pa@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("121415")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        # time.sleep(1)
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("raw@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("1152")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        time.sleep(1)
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("qaw@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("121451")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        time.sleep(1)
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("fd@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("121451")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        time.sleep(1)
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("tr@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("1214512")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        time.sleep(1)
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("low@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("sd")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        time.sleep(1)
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        time.sleep(1)
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("d@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        time.sleep(1)
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("sdsd@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        time.sleep(1)
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("alice@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        time.sleep(1)
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("zackryder@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        time.sleep(1)
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("imtiaz@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        time.sleep(1)
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("jamal@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        time.sleep(1)
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("sushant@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        time.sleep(1)
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("lashly@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        time.sleep(1)
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("bobby@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        time.sleep(1)
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("goldberg@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        time.sleep(1)
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("lesnar@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        time.sleep(1)
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("osama@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        time.sleep(1)
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("hamza@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12145")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
        driver.find_element(By.XPATH, "//input[@id='input-email']").clear()
        driver.find_element(By.CSS_SELECTOR, "#input-password").clear()































































































        time.sleep(1)
        driver.find_element(By.XPATH, "//input[@id='input-email']").send_keys("team@gmail.com")
        driver.find_element(By.CSS_SELECTOR, "#input-password").send_keys("12345")
        driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()

        driver.execute_script("window.scrollTo(100,document.body.scrollHeight);")
        time.sleep(4)
        driver.find_element(By.XPATH,"//a[@class='list-group-item'][normalize-space()='Logout']").click()
        driver.find_element(By.XPATH,"//a[normalize-space()='Continue']").click()
        driver.back()
        driver.close()




        #
        #
        #
        #
        #
        #
        #
        #
        #
        #
        #













